db:
  image: postgres
  ports:
    - "5432:5432"

web:
  build: .
  command: sh -c "/etc/service/django/djangoini.sh; python /etc/service/django/manage.py runserver 0.0.0.0:8000; tail -F /etc/hosts"
  volumes:
    - .:/code
  ports:
    - "8000:8000"
  links:
    - db
